Repository JoinColony/colonyCDapp, pull requests merged in 2022-11, with the labels that each got.

#54 Add GraphQL Voyager
  package.json
  temp-voyager/voyager.html
  temp-voyager/voyager.ts
Labels: enhancement

#80 Introduce Colony Provider
  src/components/common/ColonyHome/ColonyDomainDescription/ColonyDomainDescription.tsx
  src/components/common/ColonyHome/ColonyDomainSelector/ColonyDomainSelector.tsx
  src/components/common/ColonyHome/ColonyDomainSelector/CreateDomainButton.tsx
  src/components/common/ColonyHome/ColonyExtensions/ColonyExtensions.tsx
  src/components/common/ColonyHome/ColonyFinishDeployment/ColonyFinishDeployment.tsx
  src/components/common/ColonyHome/ColonyFundingWidget/ColonyFundingWidget.tsx
  src/components/common/ColonyHome/ColonyHome.tsx
  src/components/common/ColonyHome/ColonyHomeLayout.css
  src/components/common/ColonyHome/ColonyHomeLayout.css.d.ts
  src/components/common/ColonyHome/ColonyHomeLayout.tsx
  src/components/common/ColonyHome/ColonyMembersWidget/ColonyMembersWidget.tsx
  src/components/common/ColonyHome/ColonyNavigation/ColonyNavigation.tsx
  src/components/common/ColonyHome/ColonySubscription/ColonySubscription.tsx
  src/components/common/ColonyHome/ColonySubscription/ColonySubscriptionInfoPopover.tsx
  src/components/common/ColonyHome/ColonyTitle/ColonyTitle.tsx
  src/components/common/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.tsx
  src/components/common/ColonyHome/ColonyUpgrade/ColonyUpgrade.tsx
  src/components/common/ColonyHome/ExtensionUpgrade/ExtensionUpgrade.tsx
  src/components/common/ColonyMembers/ColonyMembers.tsx
  src/components/common/ColonyTotalFunds/ColonyTotalFunds.tsx
  src/components/common/NewActionButton/NewActionButton.tsx
  src/components/frame/ColonyBackText/ColonyBackText.tsx
  src/components/frame/RouteLayouts/UserNavigation/UserNavigation.tsx
  src/context/ColonyContext.tsx
  src/context/index.ts
  src/hooks/index.ts
  src/hooks/useCanInteractWithColony.ts
  src/hooks/useColonyContext.ts
  src/routes/Routes.tsx
Labels: section:maintenance

#77 Refactor colony home members/watchers aside
  src/components/common/ColonyHome/ColonyMembersWidget/ColonyMembersWidget.css
  src/components/common/ColonyHome/ColonyMembersWidget/MembersSubsection.tsx
  src/components/shared/Button/Button.css
  src/components/shared/Button/Button.css.d.ts
  src/components/shared/Button/Button.tsx
  src/components/shared/Button/InviteLinkButton.css
  src/components/shared/Button/InviteLinkButton.css.d.ts
  src/components/shared/Button/InviteLinkButton.tsx
  src/components/shared/Button/index.ts
  src/components/shared/ClickableHeading/ClickableHeading.css
  src/components/shared/ClickableHeading/ClickableHeading.css.d.ts
  src/components/shared/ClickableHeading/ClickableHeading.tsx
  src/components/shared/ClickableHeading/index.ts
  src/hooks/useAvatarDisplayCounter.ts
Labels: section:colony

#85 Make reputation monitor available on port 3001
  Readme.md
  docker/colony-cdapp-dev-env-orchestration.yaml
  docker/colony-cdapp-dev-env-reputation-monitor
Labels: bug

#87 Fix ganache address used for mining in local dev
  docker/files/network/run.sh.base
Labels: bug

#104 Fix GraphQL codegen issues
  src/components/common/CreateColonyWizard/StepColonyNameValidation.ts
  src/components/common/CreateColonyWizard/TokenSelector.tsx
  src/graphql/generated.ts
  src/graphql/mutations/colony.graphql
  src/graphql/mutations/token.graphql
  src/graphql/queries/token.graphql
  src/redux/sagas/colony/colonyCreate.ts
Labels: bug
