Repository JoinColony/colonyCDapp, pull requests merged in 2023-12, with the labels that each got.

#1394 Motion Flow Logic Fixes
  docker/colony-cdapp-dev-env-reputation-monitor
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VoteOutcome/VoteResults/helpers.ts
  src/components/common/ColonyActions/CountDownTimer/CountDownTimer.tsx
  src/components/common/ColonyActions/CountDownTimer/helpers.ts
  src/components/common/Extensions/ExtensionSetup/utils.ts
  src/components/frame/Extensions/pages/ExtensionDetailsPage/consts.ts
  src/components/frame/Extensions/pages/LazyConsensusPage/consts.tsx
  src/components/v5/common/ActionSidebar/hooks/useGetColonyAction.ts
  src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/consts.ts
  src/components/v5/common/ActionSidebar/partials/Motions/partials/MotionCountDownTimer/MotionCountDownTimer.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/partials/MotionCountDownTimer/hooks.ts
  src/components/v5/common/ActionSidebar/partials/Motions/partials/MotionCountDownTimer/index.ts
  src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/hooks.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/types.ts
  src/components/v5/common/ActionSidebar/partials/Motions/steps/OutcomeStep/OutcomeStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/OutcomeStep/hooks.ts
  src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/RevealStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/hooks.ts
  src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/types.ts
  src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/StakingStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/hooks.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/StakingForm.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/VotingStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/hooks.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/types.ts
  src/components/v5/common/ActionSidebar/partials/Motions/types.ts
  src/components/v5/common/CountDownTimer/helpers.ts
  src/components/v5/common/Pills/index.ts
  src/components/v5/shared/Stepper/Stepper.tsx
  src/components/v5/shared/Stepper/types.ts
  src/components/v5/shared/UserInfoSectionList/partials/UserInfoList/UserInfoList.tsx
  src/constants/extensions.ts
  src/constants/index.ts
  src/context/AppContext.tsx
  src/hooks/index.ts
  src/hooks/useUserAvatars/index.ts
  src/hooks/useUserAvatars/types.ts
  src/i18n/en.json
  src/utils/queries.ts
Labels: bug

#1491 Quick PR to completely disable dark mode
  src/routes/RootRoute.tsx
Labels: bug

#1514 Hide invite members button initially
  src/components/frame/Extensions/layouts/ColonyLayout.tsx
Labels: enhancement

#1528 Fix GTM ID being set during build
  Dockerfile
Labels: bug

#1487 Motion styling fixes #2
  src/components/common/ColonyHome/ColonyHome.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/ExitRecoveryStep/ExitRecoveryStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/RevealStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/partials/RevealInformationItem/RevealInformationItem.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/VotingStep.tsx
  src/components/v5/shared/ProgressBar/ProgressBar.tsx
  src/components/v5/shared/Stepper/Stepper.tsx
  src/components/v5/shared/Stepper/partials/StepperButton/StepperButton.tsx
  src/components/v5/shared/Stepper/partials/StepperButton/consts.ts
  src/components/v5/shared/Stepper/partials/StepperButton/types.ts
  src/images/icons/eye-closed.svg
  src/stories/shared/StepperButton.stories.tsx
Labels: bug

#1582 fix: 15639549 - searching in dropdown
  src/components/v5/shared/SearchSelect/SearchSelect.tsx
Labels: Pagepro
