Repository JoinColony/colonyCDapp, pull requests merged in 2023-07, with the labels that each got.

#703 Wire in Staked Tokens to Token Popover
  amplify/backend/api/colonycdapp/schema.graphql
  amplify/backend/function/getUserTokenBalance/src/graphql.js
  amplify/backend/function/getUserTokenBalance/src/index.js
  amplify/backend/function/getUserTokenBalance/src/package-lock.json
  amplify/backend/function/getUserTokenBalance/src/package.json
  amplify/backend/function/getUserTokenBalance/src/utils.js
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/useStakingControls.tsx
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/useEnoughTokensForStaking.ts
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/useStakingSlider.ts
  src/components/frame/RouteLayouts/UserNavigation/UserNavigation.tsx
  src/graphql/generated.ts
Labels: qa

#704 Update staked tokens after staking a motion
  docker/colony-cdapp-dev-env-block-ingestor
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/useClaimWidgetConfig.tsx
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/useObjectButton.ts
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/helpers.ts
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/useStakingInput.ts
  src/components/frame/AvatarDropdown/AvatarDropdown.tsx
  src/components/frame/AvatarDropdown/AvatarDropdownPopoverMobile.tsx
  src/components/frame/RouteLayouts/UserNavigation/UserNavigation.tsx
  src/components/frame/TokenActivation/StakesTab/ClaimAllButton.tsx
  src/components/frame/TokenActivation/TokenActivationContent/TokenActivationContent.tsx
  src/components/frame/TokenActivation/TokenActivationPopover.tsx
  src/components/frame/TokenActivation/TokensTab/ChangeTokenStateForm.tsx
  src/components/frame/TokenActivation/TokensTab/TokensTab.tsx
  src/components/frame/UserTokenActivationButton/UserTokenActivationButton.tsx
  src/context/ColonyContext.tsx
  src/context/UserTokenBalanceContext.tsx
  src/context/index.ts
Labels: qa

#709 Fix reputation in motion msg
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/useVoteDetailsConfig.tsx
  src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
Labels: qa

#713 Ensure staking slider has correct max value
  src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/helpers.ts
Labels: qa

#712 Fix error in getMembersForColony Lambda
  amplify/backend/function/getMembersForColony/src/index.js
Labels: qa

#724 Fix 2 minor README typos
  Readme.md
Labels: documentation

#719 Update funds after claim
  src/components/common/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.tsx
  src/components/common/UnclaimedTransfers/UnclaimedTransfersItem.tsx
  src/context/ColonyContext.tsx
  src/context/UserTokenBalanceContext.tsx
Labels: qa

#730 Add permission check to can upgrade extn
  src/components/common/Extensions/ExtensionUpgradeButton/ExtensionUpgradeButton.tsx
Labels: qa

#731 Consistent max colony name
  src/components/common/CreateColonyWizard/StepColonyNameInputs.tsx
  src/components/common/CreateColonyWizard/validation.ts
  src/components/common/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
  src/constants/index.ts
Labels: enhancement

#771 Fix nodejs CI
  .github/workflows/nodejs.yml
  package.json
  src/redux/sagas/wallet/onboard.ts
Labels: enhancement

#766 Fix postinstall script
  package-lock.json
  package.json
  scripts/lambda-functions-dependencies.sh
Labels: bug

#772 Use constant for annotation limit
  src/components/common/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/validation.ts
  src/components/common/Dialogs/CreateDomainDialog/CreateDomainDialog.tsx
  src/components/common/Dialogs/CreatePaymentDialog/validation.ts
  src/components/common/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialog.tsx
  src/components/common/Dialogs/EditDomainDialog/EditDomainDialog.tsx
  src/components/common/Dialogs/ManageWhitelistDialog/ManageWhitelistDialog.tsx
  src/components/common/Dialogs/MintTokenDialog/MintTokenDialog.tsx
  src/components/common/Dialogs/NetworkContractUpgradeDialog/NetworkContractUpgradeDialog.tsx
  src/components/common/Dialogs/PermissionManagementDialog/PermissionManagementDialog.tsx
  src/components/common/Dialogs/RaiseObjectionDialog/ObjectionAnnotation.tsx
  src/components/common/Dialogs/RecoveryModeDialog/RecoveryModeDialog.tsx
  src/components/common/Dialogs/TokenManagementDialog/validation.ts
  src/components/common/Dialogs/TransferFundsDialog/validation.ts
  src/components/common/Dialogs/UnlockTokenDialog/UnlockTokenDialog.tsx
  src/components/shared/Fields/Annotations/Annotations.tsx
  src/constants/index.ts
Labels: enhancement

#714 Fix `ConfirmAllInput` step
  src/components/common/CreateColonyWizard/StepConfirmAllInput.tsx
  src/components/shared/DecisionHub/DecisionOption.css
  src/components/shared/TokenSelector/TokenSelector.tsx
  src/utils/network.ts
Labels: qa

#715 Fix user name in action message
  src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
  src/components/shared/FriendlyName/FriendlyName.tsx
  src/components/shared/FriendlyName/helpers.ts
Labels: qa
