Repository JoinColony/colonyCDapp, pull requests merged in 2024-02, with the labels that each got.

#1799 fix: change richtext paragraph lineheight and lists padding
  src/components/v5/shared/RichText/partials/RichTextContent/RichTextContent.module.css
Labels: bug

#1820 fix: form prefill and team name validation
  src/components/frame/v5/pages/TeamsPage/hooks.tsx
  src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/EditTeamForm.tsx
Labels: bug

#1462 Fix: disable fields when extenstion is not installed in create decision action
  src/components/v5/common/ActionFormRow/ActionFormRow.tsx
  src/components/v5/common/ActionFormRow/types.ts
  src/components/v5/common/ActionSidebar/consts.tsx
  src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
  src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
  src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
  src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
  src/components/v5/common/ActionSidebar/partials/DescriptionField/DescriptionField.tsx
  src/components/v5/common/ActionSidebar/partials/DescriptionField/types.ts
  src/components/v5/common/ActionSidebar/partials/DescriptionRow/DescriptionRow.tsx
  src/components/v5/common/ActionSidebar/partials/DescriptionRow/types.ts
  src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx
  src/components/v5/common/ActionSidebar/partials/TeamsSelect/types.ts
  src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/CreateDecisionForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts
  src/components/v5/common/ActionSidebar/partials/hooks.ts
  src/components/v5/common/CompletedAction/partials/CreateDecision/CreateDecision.tsx
  src/components/v5/common/CompletedAction/partials/rows/Description.tsx
  src/components/v5/shared/ActionTypeNotification/ActionTypeNotification.tsx
  src/components/v5/shared/ActionTypeNotification/index.ts
  src/components/v5/shared/ActionTypeNotification/types.ts
  src/components/v5/shared/RichText/RichText.tsx
  src/components/v5/shared/RichText/types.ts
  src/i18n/en.json
  src/utils/objects/index.ts
Labels: Pagepro

#1848 Fix: Members pop over UI equal padding when no team or reputation
  src/components/v5/shared/UserPopover/partials/UserInfo.tsx
Labels: qa, UI issue

#1490 fix: edit colony details action data prefill, showing data after crea…
  src/components/shared/Fields/Form/Form.tsx
  src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
  src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
  src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/hooks.ts
  src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/types.ts
  src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/ColonyDetailsFields.tsx
  src/components/v5/common/ActionSidebar/partials/CreatedInRow/CreatedInRow.tsx
  src/components/v5/common/ActionSidebar/partials/CreatedInRow/index.ts
  src/components/v5/common/ActionSidebar/partials/CreatedInRow/types.ts
  src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/AdvancedPaymentForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/BatchPaymentForm/BatchPaymentForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/CreateDecisionForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/CreateNewTeamForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/EditColonyDetailsForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/consts.ts
  src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/hooks.ts
  src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/SocialLinksTable.tsx
  src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/hooks.tsx
  src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/types.ts
  src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/utils.tsx
  src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/EditTeamForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/ManageColonyObjectivesForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/ManageTokensForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/MintTokenForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/SimplePaymentForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/TransferFundsForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/UnlockTokenForm.tsx
  src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/UpgradeColonyForm.tsx
  src/components/v5/common/Fields/InputBase/InputBase.tsx
  src/components/v5/common/TableWithMeatballMenu/utils.tsx
  src/context/AdditionalFormOptionsContext/AdditionalFormOptionsContext.tsx
  src/context/AdditionalFormOptionsContext/index.ts
  src/i18n/en.json
  src/redux/sagas/actions/editColony.ts
  src/types/definitions/yup/index.d.ts
  src/utils/yup/customMethods.ts
  src/utils/yup/utils.ts
Labels: Pagepro

#1851 Fix: Team pill colour now correct in completed state
  src/components/v5/common/CompletedAction/partials/TransferFunds/TransferFunds.tsx
  src/components/v5/common/CompletedAction/partials/rows/TeamFrom.tsx
Labels: bug, qa, UI issue

#1867 Fix: Blockies placeholder during colony creation onboarding flow
  amplify/backend/function/fetchTokenFromChain/src/graphql.js
  src/components/common/Onboarding/wizardSteps/CreateColony/CreateColonyCardRow.tsx
  src/components/common/Onboarding/wizardSteps/CreateColony/StepCreateTokenInputs.tsx
  src/components/v5/common/AvatarUploader/partials/DefaultContent.tsx
Labels: qa, UX issue

#1887 Fix: Completed action rich text description formatting
  src/components/v5/common/ActionSidebar/consts.tsx
  src/components/v5/shared/RichTextDisplay/RichTextDisplay.module.css
  src/components/v5/shared/RichTextDisplay/RichTextDisplay.tsx
  src/i18n/en.json
Labels: bug

#1897 Fix: Calamity banner learn more link styling
  src/components/v5/shared/CalamityBanner/partials/CalamityBannerContent.tsx
Labels: qa, UI issue

#1911 Fix: Show joined colonies in the joined colonies list
  src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/hooks.ts
  src/components/frame/Extensions/layouts/partials/ColonySwitcherItem/ColonySwitcherItem.tsx
Labels: bug

#1906 Fix: Redirect to 404 when using an invalid extension name
  src/components/frame/Extensions/pages/ExtensionDetailsPage/ExtensionDetailsPage.tsx
Labels: bug

#1916 Fix: Unable to leave a colony
  src/components/v5/frame/ColonyHome/partials/LeaveColonyModal/LeaveColonyModal.tsx
  src/graphql/generated.ts
  src/graphql/queries/contributors.graphql
  src/hooks/useColonySubscription.ts
  src/hooks/useJoinedColonies.ts
Labels: bug

#1949 Fix: Action form no longer forces validation on action type change
  src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts
Labels: bug

#1967 Fix: styling for different error states
  src/components/v5/common/Fields/Input/partials/InputPills.tsx
  src/components/v5/common/Fields/InputBase/FormattedInput.tsx
  src/components/v5/common/Fields/Textarea/Textarea.tsx
  src/components/v5/shared/FormError/FormError.tsx
Labels: UI issue

#1971 Fix: Colony profile location field is not saving
  src/components/frame/v5/pages/UserProfilePage/partials/UserAccountForm/hooks.tsx
  src/components/v5/common/Fields/Input/Input.tsx
Labels: bug

#1966 Fix: Inconsistent versions of colony network and extensions
  src/components/frame/Extensions/pages/ExtensionsPage/ExtensionsPage.tsx
  src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/UpgradeColonyDescription.tsx
  src/components/v5/common/ActionSidebar/partials/ColonyVersionField/ColonyVersionField.tsx
Labels: bug

#2000 Fix: Duplicate extensions removed from tiptap config
  src/components/v5/shared/RichText/hooks.ts
  src/hooks/useRichTextEditor.ts
Labels: bug
