Repository JoinColony/colonyCDapp, pull requests merged in 2024-05, with the labels that each got.

#2352 Fix: Action process pills overlapping Userhub
  src/components/v5/shared/Modal/Modal.tsx
  src/components/v5/shared/PopoverBase/PopoverBase.tsx
  tailwind.config.js
Labels: bug

#2355 Removes usage of the payment token decimal in staking
  src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/hooks.ts
Labels: bug

#2353 Fix: useHasNoDecisionMethods hook causes edit colony details completed action to crash
  src/components/v5/common/ActionSidebar/hooks/permissions/useHasNoDecisionMethods.ts
Labels: bug, priority

#2379 Fix: Motion widgets UI regressions
  src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/OutcomeStep/partials/VoteStatuses/VoteStatuses.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/RevealStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/partials/RevealInformationItem/RevealInformationItem.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/StakingStep.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakesList/StakesList.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/VotingStep.tsx
  src/components/v5/shared/MenuWithSections/MenuWithSections.tsx
  src/components/v5/shared/UserPopover/UserPopover.tsx
  src/components/v5/shared/UserPopover/types.ts
Labels: UI issue

#2356 Fix: Use StaticJsonRpcProvider where appropriate
  amplify/backend/function/fetchColonyBalances/src/index.js
  amplify/backend/function/fetchColonyNativeFundsClaim/src/index.js
  amplify/backend/function/fetchMotionState/src/utils.js
  amplify/backend/function/fetchMotionTimeoutPeriods/src/index.js
  amplify/backend/function/fetchTokenFromChain/src/index.js
  amplify/backend/function/fetchVoterRewards/src/utils.js
  amplify/backend/function/getSafeTransactionStatus/src/index.js
  amplify/backend/function/getSafeTransactionStatus/src/utils.js
  amplify/backend/function/getUserReputation/src/index.js
  amplify/backend/function/getUserTokenBalance/src/index.js
  amplify/backend/function/qaSSMtest/src/index.js
  amplify/backend/function/updateContributorsWithReputation/src/index.js
  docker/colony-cdapp-dev-env-block-ingestor
  src/components/frame/v5/pages/UserAdvancedPage/partials/RpcForm/helpers.ts
  src/redux/sagas/motions/revealVoteMotion.ts
Labels: bug
