Repository JoinColony/colonyCDapp, pull requests merged in 2024-01, with the labels that each got.

#1678 Fix: Remove tab component top padding
  src/styles/main.global.css
Labels: good first issue

#1676 Fix: User header hover state and padding
  src/components/common/Extensions/UserHubButton/UserHubButton.tsx
  src/components/common/Extensions/UserNavigation/UserNavigation.tsx
  src/components/v5/shared/Button/Hamburger.tsx
Labels: UI issue

#1680 Fix: Update UI on Main Extensions Page
  src/components/common/Extensions/ExtensionItem/ExtensionItem.tsx
Labels: UI issue

#1683 Feat: Add clear functionality to all search inputs
  src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/ColonySwitcherContent.tsx
  src/components/v5/common/Filter/partials/SearchInput/SearchInput.module.css
  src/components/v5/common/Filter/partials/SearchInput/SearchInput.tsx
Labels: enhancement

#1698 Feat: Added copy colony address button to dashboard
  src/components/common/ColonyHome/hooks/useDashboardHeader.ts
  src/i18n/en.json
Labels: enhancement

#1701 Fixes Chromatic build workflow and adds issue templates for Github
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/workflows/chromatic.yml
Labels: bug

#1700 Fix: Add interaction states to token titles
  src/components/frame/v5/pages/BalancePage/partials/TokenAvatar/TokenAvatar.tsx
  src/components/frame/v5/pages/FundsPage/partials/TokenTable/TokenTable.tsx
Labels: UI issue

#1706 resize upload colony avatar icon
  src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/partials/ColonyAvatarField/ColonyAvatarField.tsx
  src/components/v5/common/AvatarUploader/partials/FileUpload.tsx
Labels: good first issue, UX issue

#1727 Fix: Adjust all modals positioning on desktop
  src/components/v5/shared/Modal/ModalBase.tsx
Labels: qa, UI issue

#1757 Remove scrollbar in pending transactions list
  src/components/common/Extensions/UserHub/partials/TransactionsTab/TransactionsTab.css
  src/components/common/Extensions/UserHub/partials/TransactionsTab/TransactionsTab.tsx
Labels: bug

#1783 fix: correct activity feed share link
  src/components/common/ColonyActionsTable/hooks.tsx
Labels: bug

#1728 feat: add permission roles for extensions
  src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.module.css
  src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.tsx
  src/components/v5/common/MemberCard/MemberCard.tsx
  src/components/v5/shared/RolesTooltip/RolesTooltip.tsx
  src/components/v5/shared/RolesTooltip/index.tsx
  src/components/v5/shared/RolesTooltip/types.ts
  src/i18n/en.json
Labels: Pagepro

#1798 Fix: Verified and Non-verified users actions icon
  src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
  src/components/v5/common/ActionSidebar/partials/UserSelect/hooks.ts
  src/components/v5/shared/SearchSelect/types.ts
Labels: bug, qa

#1741 Fix: Issues with upgrading colony version
  src/components/frame/Extensions/pages/AdvancedPage/AdvancedPage.tsx
  src/components/v5/common/ActionSidebar/ActionSidebar.tsx
  src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
  src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
  src/components/v5/common/ActionSidebar/partials/hooks.ts
  src/components/v5/common/CompletedAction/CompletedAction.tsx
  src/components/v5/common/CompletedAction/partials/UpgradeColonyVersion/UpgradeColonyVersion.tsx
  src/components/v5/common/CompletedAction/partials/rows/ActionType.tsx
  src/components/v5/common/CompletedAction/partials/rows/Description.tsx
  src/components/v5/shared/ColonyVersionWidget/ColonyVersionWidget.tsx
  src/components/v5/shared/ColonyVersionWidget/types.ts
  src/i18n/en-actions.ts
  src/i18n/en.json
  src/stories/shared/ColonyVersionWidget.stories.tsx
Labels: bug

#1801 fix: field label error color
  src/components/v5/common/ActionFormRow/ActionFormRow.tsx
Labels: bug

#1815 fix: SearchItem relative wrapper
  src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
Labels: bug

#1822 Fix: Teams UI optimisations
  src/components/v5/common/TeamCard/TeamCard.tsx
  src/components/v5/common/TeamCardList/TeamCardList.tsx
  src/components/v5/shared/ReputationBadge/ReputationBadge.tsx
Labels: enhancement, UI issue, UX issue
