Repository JoinColony/colonyCDapp, pull requests merged in 2025-01, with the labels that each got.

#3756 Fix Reputation Cache Update Lambda
  amplify/backend/function/fetchColonyBalances/src/package-lock.json
  amplify/backend/function/fetchColonyBalances/src/package.json
  amplify/backend/function/fetchDomainBalance/src/package-lock.json
  amplify/backend/function/fetchDomainBalance/src/package.json
  amplify/backend/function/fetchMotionState/src/package-lock.json
  amplify/backend/function/fetchMotionState/src/package.json
  amplify/backend/function/fetchMotionTimeoutPeriods/src/package-lock.json
  amplify/backend/function/fetchMotionTimeoutPeriods/src/package.json
  amplify/backend/function/fetchVoterRewards/src/package-lock.json
  amplify/backend/function/fetchVoterRewards/src/package.json
  amplify/backend/function/getUserReputation/src/package-lock.json
  amplify/backend/function/getUserReputation/src/package.json
  amplify/backend/function/getUserTokenBalance/src/package-lock.json
  amplify/backend/function/getUserTokenBalance/src/package.json
  amplify/backend/function/qaSSMtest/src/package-lock.json
  amplify/backend/function/qaSSMtest/src/package.json
  amplify/backend/function/updateContributorsWithReputation/src/graphql.js
  amplify/backend/function/updateContributorsWithReputation/src/index.js
  amplify/backend/function/updateContributorsWithReputation/src/package-lock.json
  amplify/backend/function/updateContributorsWithReputation/src/package.json
  amplify/backend/function/updateContributorsWithReputation/src/utils.js
  docker/colony-cdapp-dev-env-block-ingestor
  docker/colony-cdapp-dev-env-network
  package-lock.json
  package.json
Labels: bug, on-hold

#4100 Use correct message ID for multisig extension description
  src/constants/extensions.ts
Labels: bug

#4123 Fix CDapp Wide Transaction Gas Estimation
  src/graphql/fragments/transactions.graphql
  src/graphql/generated.ts
  src/graphql/mutations/transactions.graphql
  src/redux/actionTypes.ts
  src/redux/immutable/Transaction.ts
  src/redux/sagas/transactions/estimateGasCost.ts
  src/redux/sagas/transactions/getMetatransactionPromise.ts
  src/redux/sagas/transactions/getTransactionPromise.ts
  src/redux/sagas/transactions/transactionsToDb.ts
  src/redux/sagas/utils/getGasPrices.ts
  src/state/transactionState.ts
  src/utils/debug/debugLogging.ts
Labels: bug

#4121 Chore: Turn off notifications in dev by default
  docker/colony-cdapp-dev-env-block-ingestor
  scripts/generate-local-notifications-key.js
  src/context/Notifications/NotificationsDataContext/NotificationsDataContextProvider.tsx
Labels: enhancement

#4166 Fix (?) intermittent error in create-data script
  scripts/create-data.js
Labels: bug
